language: php
php:
  - 5.5
  - hhvm
before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests
  - CODECLIMATE_REPO_TOKEN=b47c19c0f1661ed91d5155569191bf6e05b16f7e932846885dde6f4748f790d7 ./vendor/bin/test-reporter